### ISSUE TITLE
[Suggestion] Capture error encountered when app attempts to load a model file that is not available

### ISSUE THREAD

**Issue by bidaumm** [ShinyHobo/BG3-Modders-Multitool#122]
When opening a Game Object in the Explorer without models.pak extracted, or the model file missing the following error is thrown into the logging output window

Suggestion would be to have it function similar to when the icons.pak or english.pak files are not unpacked. i.e:
```
Failed to load english.xml. Please unpack English.pak to generate translations. Skipping...
No valid texture atlases found. Unpack Icons.pak to generate icons. Skipping...
...
and any other applicable error capturing already done
```

```
[FATAL] Export failed: (3) The system cannot find the path specified: [D:\Modding\BaldursGate3\mini-extract\UnpackedData\Models\Generated\Public\Shared\Assets\Loot\Generic\LOOT_GEN_Dining_Plate_Silver_Rich_ABC\Resources\LOOT_GEN_Dining_Ustensil_Spoon_Silver_Rich_A.GR2]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
   at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at LSLib.Granny.Model.Exporter.LoadGR2(String inPath)
   at LSLib.Granny.Model.Exporter.Export()
   at Divine.CLI.CommandLineGR2Processor.ConvertResource(String file)
```

**Comment by ShinyHobo** [comment]
Updated in v0.9.2
