### ISSUE TITLE
GameObjects failed to load

### ISSUE THREAD

**Issue by RandoRuda** [ShinyHobo/BG3-Modders-Multitool#184]
```[09/06/2023 15:39:51] GameObject cache successfully cleared.
[09/06/2023 15:40:00] Opening GameObject Explorer. This could take a while.
[09/06/2023 15:40:01] Translations loaded...
[09/06/2023 15:40:01] Retrieving file list for decompression.
[09/06/2023 15:40:19] Retrived file list. Starting decompression; this could take awhile.
[09/06/2023 15:52:46] Decompression completed in 00:12:26.12.
[09/06/2023 15:52:46] Loading bank files...
[09/06/2023 15:52:47] CharacterVisualBanks found...
[09/06/2023 15:52:48] VisualBanks found...
[09/06/2023 15:52:49] MaterialBanks found...
[09/06/2023 15:52:50] TextureBanks found...
[09/06/2023 15:52:50] Sorting bank files...
[09/06/2023 15:53:50] Caching CharacterVisualBanks...
[09/06/2023 15:53:50] Caching VisualBanks...
[09/06/2023 15:53:50] Caching BodySetVisuals...
[09/06/2023 15:53:50] Caching MaterialBanks...
[09/06/2023 15:53:50] Caching TextureBanks...
[09/06/2023 15:53:50] Reading GameObjects from root templates; this will take a while...
[09/06/2023 15:54:51] GameObjects loaded...
[09/06/2023 15:54:53] Sorting GameObjects...
[09/06/2023 15:54:56] GameObjects failed to load. 895.9760493 seconds passed.
[09/06/2023 15:54:56] One or more errors occurred.
[09/06/2023 15:54:56] Specified argument was out of the range of valid values.
Parameter name: degreeOfParallelism
[09/06/2023 15:54:56]    at System.Linq.ParallelEnumerable.WithDegreeOfParallelism[TSource](ParallelQuery`1 source, Int32 degreeOfParallelism)
   at bg3_modders_multitool.Services.RootTemplateHelper.SortRootTemplate()
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()
```

**Comment by RandoRuda** [comment]
Sorry for being unable to word gooder, brain fog setting in as my meds wear off.

**Comment by ShinyHobo** [comment]
This is the second report, same location in the code. https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/154#issuecomment-1703829317

Do you happen to have Unlock Threads turned on?

**Comment by ShinyHobo** [comment]
I think I found the issue; the next build will fix this, but turn off Unlock Threads.

**Comment by RandoRuda** [comment]
> This is the second report, same location in the code. https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/154#issuecomment-1703829317
> 
> Do you happen to have Unlock Threads turned on?

Not only did I have that ticked, but I also have an AM4 series CPU. Interesting. Thanks for looking into it.
