### ISSUE TITLE
[Bug] Unable to Create Pak by Dragging Folder into Multitool.

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#245]
Getting this error when dragging most mod folders into Multitool.  Showed up with the newest update.

Error: C:\Users\Ori\AppData\Local\Temp\BG3ModPacker\LuanaTextureOverride\Public
   at Alphaleonis.Win32.Filesystem.Directory.ExistsDriveOrFolderOrFile(KernelTransaction transaction, String path, Boolean isFolder, Int32 lastError, Boolean throwIfDriveNotExists, Boolean throwIfFolderOrFileNotExists) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.ExistsDrive.cs:line 86
   at Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.FindFirstFile(String pathLp, WIN32_FIND_DATA& win32FindData, Boolean suppressException) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:line 297
   at Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.<Enumerate>d__88`1.MoveNext() in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:line 466
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Alphaleonis.Win32.Filesystem.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\DirectoryInfo Class\DirectoryInfo.GetDirectories.cs:line 103
   at bg3_modders_multitool.Services.DragAndDropHelper.ProcessLsxMerges(String directory)
   at bg3_modders_multitool.Services.DragAndDropHelper.BuildPack(String path)
   at bg3_modders_multitool.Services.DragAndDropHelper.ProcessMod(String path, String dirName)
   at bg3_modders_multitool.Services.DragAndDropHelper.<>c__DisplayClass7_0.<ProcessDrop>b__0()

**Comment by SoggyBurritoVR** [comment]
[LuanaTextureOverride.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12741384/LuanaTextureOverride.zip)

**Comment by ShinyHobo** [comment]
Fixed in 0.12.6b
