### ISSUE TITLE
System.AggregateException, while trying to open GameObject Explorer

### ISSUE THREAD

**Issue by TechRoot** [ShinyHobo/BG3-Modders-Multitool#275]
The following error appears when trying to open GameObject Explorer, it starts to load, and fails.

I've tried to redownload the app, clear indexes, cache, and rebuild all of them. Also Changed the directory where Multitool is "installed" so it does not inherit any other configuration than default values.

`[10/31/2023 08:27:12] Opening GameObject Explorer. This could take a while.
[10/31/2023 08:27:14] Loading bank files...
[10/31/2023 08:27:15] CharacterVisualBanks found...
[10/31/2023 08:27:16] VisualBanks found...
[10/31/2023 08:27:16] MaterialBanks found...
[10/31/2023 08:27:17] TextureBanks found...
[10/31/2023 08:27:17] Sorting bank files...
[10/31/2023 08:27:53] GameObjects failed to load. 40.6113465 seconds passed.
[10/31/2023 08:27:53] One or more errors occurred.
[10/31/2023 08:27:53] System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\alexc\AppData\Local\Larian Studios\Baldur's Gate 3\ExportTool-v1.18.7\BGMultitool\UnpackedData\Patch3_Hotfix2\Public\SharedDev\Content\Assets\Characters\Creatures\DEC_GEN_Corpse_Body_Pile_OrthonBed\[PAK]_DEC_GEN_Corpse_Body_Pile_OrthonBed_Head_A\_merged.lsf.lsx'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at bg3_modders_multitool.Services.RootTemplateHelper.<>c__DisplayClass63_0.<ReadVisualBanks>b__0(String visualBankFile, ParallelLoopState loopTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at bg3_modders_multitool.Services.RootTemplateHelper.ReadVisualBanks()
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__55_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__55.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\alexc\AppData\Local\Larian Studios\Baldur's Gate 3\ExportTool-v1.18.7\BGMultitool\UnpackedData\Patch3_Hotfix2\Public\SharedDev\Content\Assets\Characters\Creatures\DEC_GEN_Corpse_Body_Pile_OrthonBed\[PAK]_DEC_GEN_Corpse_Body_Pile_OrthonBed_Head_A\_merged.lsf.lsx'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at bg3_modders_multitool.Services.RootTemplateHelper.<>c__DisplayClass63_0.<ReadVisualBanks>b__0(String visualBankFile, ParallelLoopState loopTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
`

**Comment by ShinyHobo** [comment]
This will be addressed in the next patch, but I suggest you restart from scratch (delete everything except the exe), then ensure that you index using the Pak Indexer and not the Legacy Indexer.

**Comment by TechRoot** [comment]
Just a quick note:
Did as suggested, it did not work.
Also tried installing Multitool on a entire new directory so it does not inherit any configuration.

Thank you.

**Comment by ShinyHobo** [comment]
It sounds like you're repeating what you already said instead of doing what I asked. You are either doing something wrong, or your game files are corrupt. The application is very fault tolerant, and hundreds before you have this working. I do not have a timeline for when the fix will be released.

**Comment by TechRoot** [comment]
Hey!

Thank you for your kind words. In the previous message, I followed your instructions exactly, without any additions. When it didn't work, I later attempted the same in a different directory to rule out any configuration issues. Perhaps I didn't express myself correctly, or the fact that English is not my native language causes me to lose bits of information in one channel or another. However, I can certainly assure you that I haven't disregarded any instructions, and I have practically followed your guidance to no avail.

Regardless of this, I'm not asking for a timeline or a solution. I was merely providing, or attempting to provide, all the information I could to the original project author with the sole intention of offering them any relevant information.

Now that I've shared the limited information I have, you're free to completely disregard the message if you wish. As you mentioned, and considering that all other users are using it without issues, I'll find a solution on my own while you decide whether or not to fix this minor issue.

Thank you.

**Comment by ShinyHobo** [comment]
This person had the same issue and fixed by moving it out of AppData to their C drive. https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/277. I suspect the the fix that I _already have ready for the next release_ would not actually fix the problem, only mask the issue. Please try what they did.

**Comment by ShinyHobo** [comment]
I determined that it was a long filepath issue. Please update your multitool. You might still get some errors about corrupt xml files; you should be able to delete them and run it to re-extract them.

**Comment by TechRoot** [comment]
Thank you very much for your interest in resolving this matter so quickly. I've confirmed that indeed the issue was related to using long directory paths, and by moving the installation and reindexing the files, the problem disappears. I've also found that the new update allows the use of long directories without any added issues.

Thank you for your interest and attention.
