### ISSUE TITLE
DirectoryNotFoundException?

### ISSUE THREAD

**Issue by HongyuJerryWang** [ShinyHobo/BG3-Modders-Multitool#277]
Hi, thank you very much for this amazing work. Could you please help me with an issue with the GameObject Explorer? I've just newly indexed my files. Loading the GameObject Explorer returns the following error halfway:

```
[11/01/2023 21:40:43] Opening GameObject Explorer. This could take a while.
[11/01/2023 21:40:46] Loading bank files...
[11/01/2023 21:40:47] CharacterVisualBanks found...
[11/01/2023 21:40:48] VisualBanks found...
[11/01/2023 21:40:48] MaterialBanks found...
[11/01/2023 21:40:49] TextureBanks found...
[11/01/2023 21:40:49] Sorting bank files...
[11/01/2023 21:41:41] GameObjects failed to load. 58.0189156 seconds passed.
[11/01/2023 21:41:41] One or more errors occurred.
[11/01/2023 21:41:41] System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Hongyu\AppData\Local\Larian Studios\Baldur's Gate 3\bg3-modders-multitool\UnpackedData\Patch3_Hotfix2\Public\SharedDev\Content\Assets\Characters\Creatures\DEC_GEN_Corpse_Body_Pile_OrthonBed\[PAK]_DEC_GEN_Corpse_Body_Pile_OrthonBed_Head_A\_merged.lsf.lsx'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at bg3_modders_multitool.Services.RootTemplateHelper.<>c__DisplayClass63_0.<ReadVisualBanks>b__0(String visualBankFile, ParallelLoopState loopTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at bg3_modders_multitool.Services.RootTemplateHelper.ReadVisualBanks()
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__55_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__55.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Hongyu\AppData\Local\Larian Studios\Baldur's Gate 3\bg3-modders-multitool\UnpackedData\Patch3_Hotfix2\Public\SharedDev\Content\Assets\Characters\Creatures\DEC_GEN_Corpse_Body_Pile_OrthonBed\[PAK]_DEC_GEN_Corpse_Body_Pile_OrthonBed_Head_A\_merged.lsf.lsx'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at bg3_modders_multitool.Services.RootTemplateHelper.<>c__DisplayClass63_0.<ReadVisualBanks>b__0(String visualBankFile, ParallelLoopState loopTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
```

It seems to be complaining that "C:\Users\Hongyu\AppData\Local\Larian Studios\Baldur's Gate 3\bg3-modders-multitool\UnpackedData\Patch3_Hotfix2\Public\SharedDev\Content\Assets\Characters\Creatures\DEC_GEN_Corpse_Body_Pile_OrthonBed\[PAK]_DEC_GEN_Corpse_Body_Pile_OrthonBed_Head_A\_merged.lsf.lsx" could not be found, even though I've doubled checked that this file exists and can be accessed with its address through the Windows file explorer. I haven't found the cause of the problem. Could you please help me with this? Apologies in advance if it's some silly mistake I should have realised. Cheers.

**Comment by HongyuJerryWang** [comment]
Ah, as it turns out, it's a silly mistake. I installed this project under appdata, not knowing it might have been a protected directory. I moved the project under C, and all files can now be read correctly. Cheers.

**Comment by ShinyHobo** [comment]
I determined that it was a long filepath issue.
