### ISSUE TITLE
Apostrophes in meta.lsx

### ISSUE THREAD

**Issue by drkekyll** [ShinyHobo/BG3-Modders-Multitool#286]
Users of some of my mods noticed an error that I never caught because I usually pack with LSLib, but apparently an apostrophe in the meta causes the following error:

`' ' is an unexpected token. The expected token is ';'. Line 11, position 110.`

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/92404952/5c52f239-fce0-4685-875b-644fcdb237d8)

using `&apos;` (the format used in Feats.lsx) instead of the apostrophe gives the error with more:

```
[11/04/2023 17:45:34] Attempting to pack mod.
[11/04/2023 17:45:34] meta.lsx file found in 1.0.0.0\Mods\GrapplerFeat.
[11/04/2023 17:45:34] Error: ' ' is an unexpected token. The expected token is ';'. Line 11, position 110.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at bg3_modders_multitool.Services.DragAndDropHelper.ReadMeta(String meta, Nullable`1 created, Nullable`1 modGroup)
   at bg3_modders_multitool.Services.DragAndDropHelper.GenerateInfoJson(Dictionary`2 metaList)
   at bg3_modders_multitool.Services.DragAndDropHelper.<>c__DisplayClass7_0.<ProcessDrop>b__0()
[11/04/2023 17:45:34] Temp files cleaned.
[11/04/2023 17:48:57] Temp files cleaned.
[11/04/2023 17:48:57] Attempting to pack mod.
[11/04/2023 17:48:57] meta.lsx file found in 1.0.0.0\Mods\GrapplerFeat.
[11/04/2023 17:48:57] Errors found in mod workspace. Cancelling process.
```

the meta file: 
[GrapplerFeat_meta.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/13257816/GrapplerFeat_meta.zip)

**Comment by ShinyHobo** [comment]
This issue is due to your use of '&' in D&D5e. It is invalid xml due to this and expects the '&' to be closed with a ';'.
