### ISSUE TITLE
Force Closing on Unpack Game Files

### ISSUE THREAD

**Issue by velnirsworkshop** [ShinyHobo/BG3-Modders-Multitool#304]
I can't for the life of me understand why since i downloaded the latest version search index doesn't create one and when trying to unpack it force closes and i get this log.

```
Log Entry : 23:00:56 Wednesday, 06 December 2023
  :
  :An Error occured:
Stack Trace:
   at Alphaleonis.Win32.Filesystem.Directory.ExistsDriveOrFolderOrFile(KernelTransaction transaction, String path, Boolean isFolder, Int32 lastError, Boolean throwIfDriveNotExists, Boolean throwIfFolderOrFileNotExists) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.ExistsDrive.cs:line 86
   at Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.FindFirstFile(String pathLp, WIN32_FIND_DATA& win32FindData, Boolean suppressException) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:line 297
   at Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.<Enumerate>d__88`1.MoveNext() in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:line 462
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Alphaleonis.Win32.Filesystem.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.GetFiles.cs:line 119
   at bg3_modders_multitool.Services.PakReaderHelper.GetPakList()
   at bg3_modders_multitool.Services.PakUnpackHelper.UnpackSelectedPakFiles()
   at bg3_modders_multitool.Views.MainWindow.<Unpack_Click>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Message: G:\SteamLibrary\steamapps\common\Baldurs Gate 3\Data\Mods\Velnir's Workshop
-------------------------------
```

**Comment by ShinyHobo** [comment]
Probably the apostrophe in your filepath.
