### ISSUE TITLE
Crashes/unexpected closing of tool, possibly due to updating to .net framework v8? (log included)

### ISSUE THREAD

**Issue by alfa050moonshaes** [ShinyHobo/BG3-Modders-Multitool#328]
The tool worked for me, until I updated to .net framework v8 today. After doing so, it now freezes briefly then abruptly closes if I try to drag-and-drop a .pak file into the drag & drop area of the window to unpack contents.

Log states the following (the same every time):

Log Entry : 19:48:48 Friday, 09 February 2024
  :
  :An Error occured:
Stack Trace:
   at bg3_modders_multitool.ViewModels.DragAndDropBox.GetVersion()
   at bg3_modders_multitool.ViewModels.DragAndDropBox.<ProcessDrop>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Views.DragAndDropBox.<OnDrop>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Message: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=  [ ****I have removed this in case it is sensitive data**** ]  ' or one of its dependencies. The system cannot find the file specified.
-------------------------------

**Comment by ShinyHobo** [comment]
You not having the correct .net versions installed isn't something I can fix.

**Comment by alfa050moonshaes** [comment]
I understand that, but unfortunately I can't find any info on here or the wiki that tells me what .net version is required?

**Comment by ShinyHobo** [comment]
Contrary? I explicitly say not to have this utility in or near lslib in the instructions on the wiki. Glad you got it sorted out; I may improve the detection of extrnal lslib dlls due to this.
