### ISSUE TITLE
Multitool Crashing on "Lauch Game"

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#343]
`
Log Entry : 08:05:24 Wednesday, 03 April 2024
  :
  :An Error occured:
Stack Trace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at bg3_modders_multitool.Views.MainWindow.LaunchGameButton_Click(Object sender, RoutedEventArgs e) in G:\BG3\bg3-modders-multitool\bg3-modders-multitool\bg3-modders-multitool\Views\MainWindow\MainWindow.xaml.cs:line 73
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Message: An error occurred trying to start process 'bg3_dx11.exe' with working directory 'F:\Games\Baldurs Gate 3\bin'. The system cannot find the file specified.
-------------------------------`
Tried running in **Administrator Mode**.

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/daf935bb-87c4-4a55-8d31-fdc1cbd1d1ab)
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/8d6e8b89-bda2-4291-a1c8-a2e65689c4a7)

**Comment by ShinyHobo** [comment]
Will be fixed in 0.13.1
