### ISSUE TITLE
System.Exception: Stat structure file type not accounted for.

### ISSUE THREAD

**Issue by blzz** [ShinyHobo/BG3-Modders-Multitool#360]
Hi

This is on a (downloaded from here) fresh MultiTool setup. I have indexed .pak files and unpacked some game files, which went fine according to console output.

When I try to open the GameObjects explorer, this happens, and I don't know what to do about it.

Also, I do not have a "Drive G:\".

`[09/02/2024 21:39:29] Opening GameObject Explorer. This could take a while.
[09/02/2024 21:39:31] Loading CharacterVisualBanks from cache...
[09/02/2024 21:39:31] Loading VisualBanks from cache...
[09/02/2024 21:39:32] Loading BodySetVisuals from cache...
[09/02/2024 21:39:32] Loading MaterialBanks from cache...
[09/02/2024 21:39:32] Loading TextureBanks from cache...
[09/02/2024 21:39:33] Translations loaded...
[09/02/2024 21:39:33] Reading GameObjects from root templates; this will take a while...
[09/02/2024 21:39:41] GameObjects loaded...
[09/02/2024 21:39:41] GameObjects failed to load. 12.2296181 seconds passed.
[09/02/2024 21:39:41] One or more errors occurred. (Stat structure file type 'Public/CommunityLibrary/Stats/Generated/Data/__MT_GEN_CL_Class_Specific_1722412268891.txt' not accounted for.)
[09/02/2024 21:39:41] System.Exception: Stat structure file type 'Public/CommunityLibrary/Stats/Generated/Data/__MT_GEN_CL_Class_Specific_1722412268891.txt' not accounted for.
   at bg3_modders_multitool.Models.StatStructures.StatStructure.FileType(String file) in G:\BG3\bg3-modders-multitool\bg3-modders-multitool\bg3-modders-multitool\Models\StatStructures\StatStructure.cs:line 62
   at bg3_modders_multitool.Services.RootTemplateHelper.ReadData() in G:\BG3\bg3-modders-multitool\bg3-modders-multitool\bg3-modders-multitool\Services\RootTemplateHelper.cs:line 522
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__55_0() in G:\BG3\bg3-modders-multitool\bg3-modders-multitool\bg3-modders-multitool\Services\RootTemplateHelper.cs:line 122
   at System.Threading.Tasks.Task 1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at bg3_modders_multitool.Services.RootTemplateHelper.LoadRootTemplates() in G:\BG3\bg3-modders-multitool\bg3-modders-multitool\bg3-modders-multitool\Services\RootTemplateHelper.cs:line 108
`

This leads to an empty GameObject explorer with a greyed out dropdown menu.

**Comment by ShinyHobo** [comment]
Mods are not supported in the GOE. You have to remove your mod paks from the data folder as indicated by the presence of "__MT_GEN_CL_Class_Specific_1722412268891" in the error output.
