### ISSUE TITLE
Add loading spinner to GameObject Explorer (GameObject Explorer always return 0 result)

### ISSUE THREAD

**Issue by Dapoulp** [ShinyHobo/BG3-Modders-Multitool#92]
Despite unpacking, decompressing and indexing, when I choose a GameObject Type, there is no object at all displayed and it says "0 results".
Did I miss something or is there a problem with the tool ?

**Comment by ShinyHobo** [comment]
This should be fixed as of v0.8.2.

**Comment by jwvanderbeck** [comment]
Every time I've tried this feature I just get come errors about loading certain files and nothing shows in the window

```Loading GameObjects...
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Patch8_HF5\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Patch8_HF3\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
```

**Comment by jwvanderbeck** [comment]
So it took a while but in the end I think it "finished" but still nothing shows up

```Loading GameObjects...
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Patch8_HF5\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Patch8_HF3\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Shared\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
Failed to load D:\Games\BG3 Modding\bg3-modders-multitool-0.8.2\UnpackedData\Patch8_HF4\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
GameObjects failed to load. 49.7968285 seconds passed.
One or more errors occurred.
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at bg3_modders_multitool.Services.RootTemplateHelper.ReadVisualBanks()
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()
Caching CharacterVisualBanks...
Caching VisualBanks...
Caching BodySetVisuals...
Caching MaterialBanks...
Caching TextureBanks...
Sorting GameObjects...
Caching GameObjects...
GameObjects loaded in 572.7024463 seconds.```

**Comment by jwvanderbeck** [comment]
Ok so I think I got this working.  For anyone else having similar issues, tl;dr I closed the application, deleted the cache directory, reran it and selected the GO explorer then just left it untouched for about 10 minutes.

I think originally when I didn't realize it had all this work to do I had opened the explorer, saw nothing, then closed it which basically screwed it all up.

**Comment by exoticpirate** [comment]
I tried the same solution... no luck. I have a decent PC build i9 11900k @3.5 ghz , 64 GB Ram and a 3080 RTX vid card ... so 30 minutes should have been enough time right?

Loading GameObjects...
Failed to load E:\B3Patch9\ExportTool-v1.15.15\ExportTool-v1.15.15\UnpackedData\Shared\Public\Shared\Content\Assets\Characters\Creatures\Dog\[PAK]_Body\_merged.lsx.
Caching CharacterVisualBanks...
Caching VisualBanks...
Caching BodySetVisuals...
Caching MaterialBanks...
Caching TextureBanks...
GameObjects failed to load. 108.7539862 seconds passed.
One or more errors occurred.
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at bg3_modders_multitool.Services.RootTemplateHelper.ReadRootTemplate()
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()

**Comment by ShinyHobo** [comment]
The latest game update probably broke it again. This process normally only takes me 2-3 minutes.
